# Generated by Django 3.1.8 on 2021-10-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('cameratype', models.CharField(max_length=20)),
            ],
        ),
    ]
